# See https://docs.ansible.com/ansible/latest/dev_guide/collections_galaxy_meta.html

namespace: scaleway
name: scaleway
version: 2.7.0
readme: README.md
authors:
  - Ansible (https://github.com/ansible)
  - Scaleway (https://github.com/scaleway)
  - Nathanael Demacon (https://github.com/quantumsheep)
description: Scaleway Ansible Collection.
license_file: LICENSE
tags:
  - scaleway
  - cloud
  - compute
  - instances
repository: https://github.com/scaleway/ansible
homepage: https://github.com/scaleway/ansible
issues: https://github.com/scaleway/ansible/issues
build_ignore:
  - .gitignore
  - changelogs/.plugin-cache.yaml
  - .DS_Store
  - "*.tar.gz"
  - "plugins/modules/scaleway_account_project.py"
  - "plugins/modules/scaleway_applesilicon_server.py"
  - "plugins/modules/scaleway_baremetal_server.py"
  - "plugins/modules/scaleway_container_cron.py"
  - "plugins/modules/scaleway_container_domain.py"
  - "plugins/modules/scaleway_container_namespace.py"
  - "plugins/modules/scaleway_container_token.py"
  - "plugins/modules/scaleway_container.py"
  - "plugins/modules/scaleway_domain_ssl_certificate.py"
  - "plugins/modules/scaleway_flexibleip_flexible_ip.py"
  - "plugins/modules/scaleway_function_cron.py"
  - "plugins/modules/scaleway_function_domain.py"
  - "plugins/modules/scaleway_function_namespace.py"
  - "plugins/modules/scaleway_function_token.py"
  - "plugins/modules/scaleway_function_trigger.py"
  - "plugins/modules/scaleway_function.py"
  - "plugins/modules/scaleway_iam_api_key.py"
  - "plugins/modules/scaleway_iam_application.py"
  - "plugins/modules/scaleway_iam_group.py"
  - "plugins/modules/scaleway_iam_policy.py"
  - "plugins/modules/scaleway_iam_ssh_key.py"
  - "plugins/modules/scaleway_instance_image.py"
  - "plugins/modules/scaleway_instance_ip.py"
  - "plugins/modules/scaleway_instance_placement_group.py"
  - "plugins/modules/scaleway_instance_private_nic.py"
  - "plugins/modules/scaleway_instance_security_group_rule.py"
  - "plugins/modules/scaleway_instance_security_group.py"
  - "plugins/modules/scaleway_instance_snapshot.py"
  - "plugins/modules/scaleway_instance_volume.py"
  - "plugins/modules/scaleway_iot_device.py"
  - "plugins/modules/scaleway_iot_hub.py"
  - "plugins/modules/scaleway_iot_network.py"
  - "plugins/modules/scaleway_iot_route.py"
  - "plugins/modules/scaleway_lb_acl.py"
  - "plugins/modules/scaleway_lb_backend.py"
  - "plugins/modules/scaleway_lb_certificate.py"
  - "plugins/modules/scaleway_lb_frontend.py"
  - "plugins/modules/scaleway_lb_route.py"
  - "plugins/modules/scaleway_lb_subscriber.py"
  - "plugins/modules/scaleway_lb.py"
  - "plugins/modules/scaleway_mnq_credential.py"
  - "plugins/modules/scaleway_mnq_namespace.py"
  - "plugins/modules/scaleway_rdb_database_backup.py"
  - "plugins/modules/scaleway_rdb_endpoint.py"
  - "plugins/modules/scaleway_rdb_instance.py"
  - "plugins/modules/scaleway_rdb_read_replica.py"
  - "plugins/modules/scaleway_rdb_snapshot.py"
  - "plugins/modules/scaleway_redis_cluster.py"
  - "plugins/modules/scaleway_registry_namespace.py"
  - "plugins/modules/scaleway_vpcgw_dhcp_entry.py"
  - "plugins/modules/scaleway_vpcgw_dhcp.py"
  - "plugins/modules/scaleway_vpcgw_gateway_network.py"
  - "plugins/modules/scaleway_vpcgw_gateway.py"
  - "plugins/modules/scaleway_vpcgw_ip.py"
  - "plugins/modules/scaleway_vpcgw_pat_rule.py"
