[project]
name = "ansible"
version = "2.7.0"
requires-python = ">=3.8"

[tool.poetry.group.dev.dependencies]
ty = "^0.0.1a15"
pyrefly = "^0.24.2"

[tool.ty.rules]
unresolved-import = "ignore"
unresolved-attribute = "ignore"
possibly-unbound-attribute = "ignore"
no-matching-overload = "ignore"
invalid-argument-type = "ignore"
invalid-return-type = "ignore"

[tool.pyrefly.errors]
import-error = false
missing-attribute = false
bad-assignment = false
no-matching-overload = false
bad-override = false
bad-argument-type = false
bad-return = false
