[project]
name = "ansible"
version = "2.7.0"
requires-python = ">=3.8"

[tool.poetry]
package-mode = false

[tool.poetry.group.dev.dependencies]
ty = "^0.0.1a15"
pyrefly = "^0.24.2"
ruff = "^0.12.4"

[tool.ruff.lint]
ignore = [
    "BLE001",
    "C401",
    "C405",
    "C408",
    "E402",
    "EXE001",
    "FA100",
    "FA102",
    "I001",
    "RUF019",
    "TRY201",
    "UP001",
    "UP004",
    "UP008",
    "UP009",
    "UP010"
]

[tool.ty.rules]
unresolved-import = "ignore"
unresolved-attribute = "ignore"
possibly-unbound-attribute = "ignore"
no-matching-overload = "ignore"
invalid-argument-type = "ignore"
invalid-return-type = "ignore"

[tool.pyrefly.errors]
import-error = false
missing-attribute = false
bad-assignment = false
no-matching-overload = false
bad-override = false
bad-argument-type = false
bad-return = false
