# We only support ansible-core versions that are not EOL
# https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html

name: units

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  units:
    timeout-minutes: 30
    name: Units (Ⓐ$${{ matrix.ansible-version }})
    strategy:
      fail-fast: false
      matrix:
        ansible-version:
          - stable-2.19
          - stable-2.17
          - stable-2.18
    env:
     ansible-collections-path: "./ansible_collections/scaleway/scaleway"

    runs-on: ubuntu-latest
    steps:
      - name: Create directory
        run: |
          mkdir -p ${{ env.ansible-collections-path }}

      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          path: ${{ env.ansible-collections-path }}

      - name: Setup Python and install ansible
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install ansible
        run: |
          python -m pip install \
            https://github.com/ansible/ansible/archive/${{ matrix.ansible-version }}.tar.gz \
            --disable-pip-version-check

      - name: Run unit tests with ansible ${{ matrix.ansible-version }}
        working-directory: ${{ env.ansible-collections-path }}
        run: |
          ansible-test units -v --requirements