name: Release

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    name: Publish to Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install Ansible
        run: pip install ansible

      - name: Install antsibull-changelog
        run: pip install antsibull-changelog

      - name: Set galaxy.yml version
        run: |
          sed -i -e "s/version:.*/version: ${{ github.ref_name }}/" galaxy.yml

      - name: Build changelog
        run: antsibull-changelog release

      - name: Build collection
        run: ansible-galaxy collection build

      - name: Build and publish collection to Galaxy
        run: ansible-galaxy collection publish --api-key ${{ secrets.GALAXY_API_KEY }} scaleway-scaleway-${{ github.ref_name }}.tar.gz

      - name: Create a release with the collection artifact
        uses: softprops/action-gh-release@v1
        with:
          files: |
            scaleway-scaleway-${{ github.ref_name }}.tar.gz
          generate_release_notes: true

      - name: Create a PR to update changelog
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "docs: update changelog for ${{ github.ref_name }}"
          title: "docs: update changelog for ${{ github.ref_name }}"
          body: |
            Update changelog for ${{ github.ref_name }}
          branch: docs/update-changelog-${{ github.ref_name }}
          delete-branch: true
          base: main
